version: '3'
services:
  master-account:
    build: ./ms-masteraccount
    ports:
      - "8081:8081"
    networks:
      - app-network
  orquestador:
    build: ./ms-orquestador
    ports:
      - "8082:8082"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge