spring:
  application:
    name: ms-masteraccount
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: ${DBCP_MSDB_URL}
    username: ${DBCP_MSDB_USER}
    password: ${DBCP_MSDB_PASS}
    driver-class-name: ${DBCP_MSDB_DRIVER}

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


